// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrwajkptntnohxsnvayp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxyd2Fqa3B0bnRub2h4c252YXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTIzOTMsImV4cCI6MjA2MjgyODM5M30.ANAu1Vgbw0Rhnd9mhJrCeecBuAvn1adz-hEzeDUf9mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
